package com.example.domain.scanner

enum class MathChapter {
    SETS_RELATIONS_FUNCTIONS,
    COMPLEX_NUMBERS_QUADRATIC_EQUATIONS,
    MATRICES_DETERMINANTS,
    PERMUTATIONS_COMBINATIONS,
    MATHEMATICAL_INDUCTION,
    BINOMIAL_THEOREM,
    SEQUENCE_SERIES,
    LIMIT_CONTINUITY_DIFFERENTIABILITY,
    INTEGRAL_CALCULUS,
    DIFFERENTIAL_EQUATIONS,
    COORDINATE_GEOMETRY,
    THREE_DIMENSIONAL_GEOMETRY,
    VECTOR_ALGEBRA,
    STATISTICS_PROBABILITY,
    TRIGONOMETRY,
    MATHEMATICAL_REASONING,
    GENERAL
}
